#!/usr/bin/php
<?php

set_include_path(get_include_path() . PATH_SEPARATOR . "/usr/local/mgr5/include/php");
define('__MODULE__', "pmparkingerip");

require_once 'bill_util.php';

$longopts  = array
(
    "command:",
    "payment:",
    "amount:",
);

$options = getopt("", $longopts);

try {
	$command = $options['command'];
	Debug("command ". $options['command']);

	if ($command == "config") {
		$config_xml = simplexml_load_string($default_xml_string);
		$feature_node = $config_xml->addChild("feature");

		// $feature_node->addChild("refund", 		"on");
		// $feature_node->addChild("transfer", 		"on");
        $feature_node->addChild("redirect", 		"on");
		// $feature_node->addChild("noselect", 		"on");
 		$feature_node->addChild("notneedprofile", 	"on");

		// $feature_node->addChild("pmtune", 			"on");
        $feature_node->addChild("pmvalidate", 		"on");

		// $feature_node->addChild("crtune", 			"on");
         $feature_node->addChild("crvalidate", 		"on");
 		// $feature_node->addChild("crset", 			"on");
		// $feature_node->addChild("crdelete", 		"on");

		// $feature_node->addChild("rftune", 			"on");
		// $feature_node->addChild("rfvalidate", 		"on");
		// $feature_node->addChild("rfset", 			"on");

		// $feature_node->addChild("tftune", 			"on");
		// $feature_node->addChild("tfvalidate", 		"on");
		// $feature_node->addChild("tfset", 			"on");

        $param_node = $config_xml->addChild("param");

		 $param_node->addChild("payment_script", "/mancgi/easypaypayment.php");

		echo $config_xml->asXML();
	} elseif ($command == "pmtune") {
	// 	$paymethod_form = simplexml_load_string(file_get_contents('php://stdin'));
	// 	$pay_source = $paymethod_form->addChild("slist");
	// 	$pay_source->addAttribute("name", "pay_source");
	// 	$pay_source->addChild("msg", "qw");
	// 	$pay_source->addChild("msg", "mobile");
	// 	echo $paymethod_form->asXML();
		$form = file_get_contents('php://stdin');
		Debug($form);
		return $form;
	} elseif ($command == "pmvalidate") {
		$paymethod_form = simplexml_load_string(file_get_contents('php://stdin'));
		Debug($paymethod_form->asXML());

		$MER_NO = $paymethod_form->MER_NO;
		$WEB_KEY = $paymethod_form->WEB_KEY;

        DEBUG("MER_NO: $MER_NO");
        if (!preg_match("/^ok\d{4}$/", $MER_NO)) {
			throw new billmgrErrorException("value", "MER_NO", $MER_NO);
		}

        //TODO узнать формат web-ключа

		echo $paymethod_form->asXML();
	} elseif ( $command == "crvalidate" ) {
        $payment_form = simplexml_load_string(file_get_contents('php://stdin'));
		$ok = $payment_form->addChild("ok", "/mancgi/easypaypayment.php?elid=" . $payment_form->payment_id);
		$ok->addAttribute("type", "5");
		echo $payment_form->asXML();
    }
    else {
		throw new BillmgrError("unknown command");
	}
} catch (Exception $e) {
	echo $e;
}
